### ISSUE TITLE
Symbol's function definition is void: mm-url-encode-www-form-urlencoded

### ISSUE THREAD

**Issue by nyameko** [larsmagne/imgur.el#1]
Hello,

I receive the following error when trying to run `M-x imgur-upload-image`

``` emacs-lisp
Symbol's function definition is void: mm-url-encode-www-form-urlencoded
```

The contents of my init.org are as follows:

``` emacs-lisp
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/github/imgur/")
(require 'imgur)
#+END_SRC
```

where I have added your [imgur.el](https://github.com/larsmagne/imgur.el/) repository as a git submodule at the path `~/.emacs.d/github/imgur/`

Thank you

**Comment by nyameko** [comment]
Sorry,

Not running the latest build of emacs-git, I'm current on '''emacs-git 25.1.50.r126117-1`, and am assuming this has the same requirements as`meme.el```...?

Anyway, marking this as closed.

**Comment by larsmagne** [comment]
No, it was just a bug.  :-)  It should require mm-url, and it didn't.  I've now fixed that.
